name: mmp
channels:
  - conda-forge
  - pytorch
  - menpo
  - nvidia
  - contango
  - grst            # supplies rectangle-packer, required by lbs_pytorch
  - pytorch3d       # supplies pytorch3d, required by lbs_pytorch
  - omnia           # supplies eigen3, required by care_extensions
  - fastai          # supplies python-opencv-headless, required by care
  - ./conda_build   # supplies lbs_pytorch, pyplymeshio, airstore, drtk, care_extensions
  - open3d-admin    # supplies open3d
dependencies:
  - memray
  - python
  - pillow
  - rectangle-packer
  - jpeg
  - libjpeg-turbo
  - libtiff
  - libpng
  - libwebp
  - numpy
  - scipy
  - blas=*=mkl
  - mkl
  - mkl-include
  - pytorch=2.0.0=py3.8_cuda11.8_cudnn8.7.0_0
  - cudatoolkit=11.8
  - torchaudio
  - torchvision
  - cudnn=8.2.0
  - tensorboard>=2.5
  - tensorboardx>=2.2
  - pytorch-lightning>=1.5
  - magma-cuda110
  - aiofiles
  - aiohttp
  - argcomplete
  - black
  - bleach
  - cmake
  - coverage
  - cython
  - ffmpeg
  - x264
  - flake8
  - opencv
  - libopencv
  - py-opencv
  - kornia
  - meshio
  - libmad
  - git
  - ffmpeg-python
  - openssh
  - emacs
  - fish
  - nano
  - tmux
  - ipdb
  - attrdict
  - pyembree
  - embree3
  - python-embree
  - xxhash
  - shapely
  - rtree
  - importlib_resources
  - sqlalchemy=1.4.*
  - dacite
  - python-xxhash
  - scikit-image
  - mir_eval
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numba
  - zipp
  - unzip
  - python-rocksdb
  - pandas>=1.4,<2.0
  - psutil
  - pylint
  - pysoundfile
  - python-lmdb
  - lmdb
  - antlr-python-runtime=4.9.3
  - antlr4-python3-runtime=4.9.3
  - igl
  - gitpython
  - gpustat
  - nvidia-ml
  - ipython
  - jsondiff
  - jupyter
  - librosa
  - line_profiler
  - objprint
  - viztracer
  - ipykernel
  - ipython
  - matplotlib
  - tqdm
  - trimesh
  - pybind11
  - cftime
  - netcdf4
  - zope.interface
  - imgaug
  - xorg-libxrandr
  - tbb
  - tbb-devel
  - the_silver_searcher
  - imageio-ffmpeg
  - libcxxabi
  - libcxx
  - configargparse
  - meshplot
  - plyfile
  - fsspec
  - future
  - pytz
  - onnx
  - opt_einsum
  - av
  - addict
  - sacrebleu
  - dataclasses
  - portalocker
  - parallel
  - janus
  - ftfy
  - typed-argument-parser
  - pprofile
  - semver
  - imagemagick
  - sympy
  - pytest
  - gtest
  - gmock
  - alembic
  - dlib
  - retry
  - sox
  - ninja
  - glew
  - glfw
  - eigen
  - gflags
  - glog
  - boost
  - zstd
  - zstandard
  - pyopengl
  - moderngl
  - mesa
  - mesalib
  - bitarray
  - gast
  - astunparse
  - flatbuffers
  - python-flatbuffers
  - timm
  - debugpy
  - freetype
  - pymongo
  - fvcore
  - tabulate
  - yacs
  - pyyaml
  - dominate
  - pydot
  - pygraphviz
  - python-graphviz
  - pydantic
  - dnspython
  - tinydb
  - conda-build
  - conda-verify
  - mpi
  - mpich
  - mpi4py
  - omegaconf
  # - python_speech_features  # Something broke with this, come back to it later
  - hydra-core
  - sox
  - tensorflow-cpu
  - botorch
  - multipledispatch
  - gpytorch
  - transformers
  - diffusers
  - torchmetrics
  - airstore
  - drtk
  - care
  - care_extensions
  - lbs_pytorch
  - pyplymeshio
  - einops
  - boto3
  - open3d=0.13.*
  - plyloader
  - iopath>=0.1.10
  - data_manifest
  - structlog
  - scikit-sparse
  - py-spy
  - pip:
    - theseus-ai
    - python-sofa
    - pyroomacoustics
    - pesq
    - pystoi
    - inplace_abn
    - warmup_scheduler
    - pyexr
    - pysdf
    - torch-tb-profiler
    - linear_operator
    - lion-pytorch==0.0.6
    - pygltflib
    - timm 
    - einops 
    - pycocotools
    - chumpy 
    - scipy 
    - munkres 
    - yapf==0.40.1
    - openmim
    - model-index
    - modelindex
    - ordered-set
    - mat4py
    - setuptools
    - xtcocotools